/* =====================================================================
   산불 대응 AI 의사결정 지원 시스템 목업 — 시나리오 데이터 (2025-03-22 의성 산불)
   ---------------------------------------------------------------------
   real: true  → 공개 자료에서 가져온 값(출처는 note/meta.sources)
   real: false → 구하지 못해 만든 시연용 가상값
   좌표는 [경도, 위도] (WGS84)
   ===================================================================== */
window.SCENARIO = {
  meta: {
    id: "UISEONG-2025-03-22",
    title: "2025-03-22 의성 산불 (안평면 괴산리) — 발생 후 8시간",
    now: "2025-03-22T12:00:00+09:00", // 시연 기준 현재 시각(t0). 예측은 이 시각부터 +8h
    horizon_hours: 8,
    stage_scheme_note:
      "2025년 당시는 구 1·2·3단계 체계였으나 목업은 2026년 개편 체계(초기대응·확산대응 1·2단계)로 표시한다.",
    spread_note:
      "P1~P8 화선은 실제 관측 화선이 아니라 발화점·풍향·풍속으로 만든 합성 타원이다. 상황 보고자가 입력한 실측 화선 폴리곤이 있으면 그 범위를 포함하도록 확장한다.",
    sources: [
      {
        id: "S1",
        label: "산림청 X(2025-03-22 22:00 상황): 11:25 안평면 괴산리 발생",
        url: "https://x.com/forest_news/status/1903457349572129015",
      },
      {
        id: "S2",
        label: "산림청 X(2025-03-23 15:00 상황): 발생지 괴산리 산61 일원",
        url: "https://x.com/forest_news/status/1903700317457555645",
      },
      {
        id: "S3",
        label:
          "이데일리 2025-03-22 17:42 종합: 헬기 27·차량 36·인력 375, 대피 200명(요양병원 70여명 포함), 풍속 5.6 m/s",
        url: "https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=01846646642105944",
      },
      {
        id: "S4",
        label:
          "위키백과 2025년 의성-안동 산불: 11:24 신고, 철파리·방하리 주민 대피",
        url: "https://ko.wikipedia.org/wiki/2025%EB%85%84_%EC%9D%98%EC%84%B1-%EC%95%88%EB%8F%99_%EC%82%B0%EB%B6%88",
      },
      {
        id: "S5",
        label:
          "OpenStreetMap(Overpass API): 마을·면사무소·학교·사찰·복지시설 좌표, 도로·철도 선형, 저수지",
        url: "https://www.openstreetmap.org/copyright",
      },
      {
        id: "S6",
        label: "국가데이터처 SGIS 행정구역 경계(2025.2Q)·인구총괄(2024)",
        url: "https://sgis.kostat.go.kr/",
      },
      {
        id: "S7",
        label:
          "「산불 재난」 위기관리 표준매뉴얼(2026.6 일부개정) 본문 쪽수 — 근거 텍스트는 요약(원문 비공개)",
        url: "",
      },
    ],
  },

  // 산불 목록(UC-SIT-02). 진행 중 1건(실제 사건) + 접수 1건·종료 1건(가상, 목록 시연용)
  // 상태: 접수 → 진행 중(실측 화선이 처음 저장되면) → 종료. start_time(발생 일시)은 접수 단계에서 비어 있을 수 있고 report_time(신고 접수 일시)은 필수
  // intake: 기관별 접수 기록(접수 기관·접수 시각·접수 경로) — 상황 보고자가 산불 상황 보고 때 입력
  // perimeters: 실측 화선 버전 목록(v1, v2 …). status 유효 / 정정됨(정정 제출 시 이전 버전은 '정정됨'으로 보존). 최신 '유효' 버전이 예측의 시작점
  incidents: [
    {
      id: "F-2025-0322-01",
      name: "의성 안평면 산불",
      status: "진행 중",
      real: true,
      addr: "경북 의성군 안평면 괴산리 산61 일원",
      ignition: [128.60226, 36.36565], // 괴산리 마을 중심(OSM). 실제 발화지 '산61 일원'은 야산 정상부
      start_time: "2025-03-22T11:24:00+09:00", // 발생 11:24 · 신고 11:25(보도 기준)
      report_time: "2025-03-22T11:25:00+09:00",
      report_text:
        "119 신고 — 괴산리 뒷산 정상부 연기·불꽃 목격, 성묘객 실화 추정(보도)",
      reported_by: "rep01",
      // P5 기준 위험도 화면 비교용 시연 데이터
      risk_demo_runs: [
        {
          missing_vars: [],
          scores: {
            weather: 4.2,
            terrain: 3.6,
            fuel: 3.9,
            infra: 2.4,
          },
          values: {
            weather: "풍속 5.6 m/s · 풍향 240° · 습도 24% · 기온 19℃",
            terrain: "경사 21° · 남서 사면 · 고도 230 m",
            fuel: "침엽수림(소나무) · 임목 밀도 높음 · 낙엽층 두꺼움",
            infra:
              "취약계층 120명(65세 이상 100명·0~14세 20명) · 최근 화선 기준 가장 가까운 소방서까지 거리 3.2 km",
          },
        },
        {
          missing_vars: [],
          scores: {
            weather: 4.5,
            terrain: 3.8,
            fuel: 4.1,
            infra: 3.0,
          },
          values: {
            weather: "풍속 7.0 m/s · 풍향 250° · 습도 20% · 기온 20℃",
            terrain: "경사 24° · 남서 사면 · 고도 260 m",
            fuel: "침엽수림(소나무) · 임목 밀도 높음 · 낙엽층 두꺼움",
            infra:
              "취약계층 180명(65세 이상 150명·0~14세 30명) · 최근 화선 기준 가장 가까운 소방서까지 거리 4.1 km",
          },
        },
      ],
      intake: [
        {
          org: "의성군(119 공동대응)",
          at: "11:25",
          channel: "119 신고",
          real: true,
        },
        {
          org: "경북도 산림재난상황실",
          at: "11:31",
          channel: "상황 전파",
          real: false,
        },
        {
          org: "남부지방산림청",
          at: "11:34",
          channel: "상황 전파",
          real: false,
        },
        {
          org: "산림청 중앙산림재난상황실",
          at: "11:38",
          channel: "상황 전파",
          real: false,
        },
      ],
      official_stage: "초기대응",
      alert_level: "주의",
      // 상황 보고자가 입력한 실측 화선 v1(가상 12.7 ha, 발화점 북동쪽으로 진행). 예측은 이 범위를 포함하도록 확장된다
      perimeters: [
        {
          version: 1,
          status: "유효",
          at: "2025-03-22T11:55:00+09:00",
          by: "rep01",
          source: "지도 그리기",
          real: false,
          ring: [
            [128.60512, 36.36565],
            [128.60548, 36.36691],
            [128.60428, 36.3677],
            [128.60299, 36.36825],
            [128.60156, 36.36815],
            [128.60071, 36.36722],
            [128.60058, 36.36631],
            [128.60104, 36.36565],
            [128.60138, 36.36531],
            [128.6013, 36.36467],
            [128.60194, 36.36451],
            [128.60254, 36.36467],
            [128.60313, 36.36476],
            [128.60369, 36.36509],
            [128.60512, 36.36565],
          ],
        },
      ],
      field_report: { expected_suppression_hours: null }, // 예상 진화시간(상황 정정으로 입력)
      evacuation_state: {
        order_issued: false,
        cbs_sent: [],
        completed_villages: [],
        injuries: [],
      },
      ended_at: null,
      ended_by: null,
    },
    {
      id: "F-2025-0322-02",
      name: "의성 사곡면 산불(가상)",
      status: "접수",
      real: false,
      addr: "경북 의성군 사곡면 양지리 일원(가상)",
      ignition: [128.752, 36.341],
      start_time: null,
      report_time: "2025-03-22T11:52:00+09:00",
      report_text:
        "주민 신고 — 논두렁 소각 중 인접 야산으로 연소 확대 의심. 현장 확인 중",
      reported_by: "rep01",
      intake: [
        {
          org: "의성군(119 공동대응)",
          at: "11:52",
          channel: "119 신고",
          real: false,
        },
      ],
      official_stage: "초기대응",
      alert_level: "주의",
      perimeters: [],
      risk_scores: { weather: 3.9, terrain: 3.2, fuel: 3.5, infra: 2.6 },
      field_report: { expected_suppression_hours: null },
      evacuation_state: {
        order_issued: false,
        cbs_sent: [],
        completed_villages: [],
        injuries: [],
      },
      ended_at: null,
      ended_by: null,
    },
    {
      id: "F-2025-0321-01",
      name: "의성 점곡면 산불(가상)",
      status: "종료",
      real: false,
      addr: "경북 의성군 점곡면 서변리 일원(가상)",
      ignition: [128.725, 36.433],
      start_time: "2025-03-21T13:05:00+09:00",
      report_time: "2025-03-21T13:10:00+09:00",
      report_text:
        "농산부산물 소각 부주의(추정). 0.3 ha, 지상진화로 당일 진화 완료",
      reported_by: "rep01",
      intake: [
        {
          org: "의성군(119 공동대응)",
          at: "13:10",
          channel: "119 신고",
          real: false,
        },
      ],
      official_stage: "초기대응",
      alert_level: "관심",
      perimeters: [],
      // 종료된 산불의 시연 데이터. 위험도 화면에서는 숫자 대신 종료를 표시한다
      risk_scores: { weather: 3.4, terrain: 3.0, fuel: 3.2, infra: 2.8 },
      field_report: { expected_suppression_hours: 6 },
      evacuation_state: {
        order_issued: false,
        cbs_sent: [],
        completed_villages: [],
        injuries: [],
      },
      ended_at: "2025-03-21T18:40:00+09:00",
      ended_by: "cmd01",
    },
  ],

  // 대응단계 판정: 표준매뉴얼 p.73 판단기준 4요소(예상 피해면적·평균풍속·예상 진화시간·시설피해) 중 가장 높은 단계
  // 구간값은 산림재난방지법 시행령 별표(구 1·2·3단계)의 기준값을 2026 개편 체계에 대응시킨 목업 근사값
  stage_rules: {
    area_ha: [
      { stage: "초기대응", max: 10 },
      { stage: "확산대응 1단계", min: 10, max: 100 },
      { stage: "확산대응 2단계", min: 100 },
    ],
    wind_ms: [
      { stage: "초기대응", max: 4 },
      { stage: "확산대응 1단계", min: 4, max: 7 },
      { stage: "확산대응 2단계", min: 7 },
    ],
    hours: [
      { stage: "초기대응", max: 8 },
      { stage: "확산대응 1단계", min: 8, max: 24 },
      { stage: "확산대응 2단계", min: 24 },
    ],
    // 시설피해 우려(P5 안 주택·주요시설 동수): 주택 1동 이상 → 1단계, 주요시설(취약시설·국가유산) 1동 이상 또는 주택 30동 이상 → 2단계
    facility: { stage1_houses: 1, stage2_houses: 30, stage2_major: 1 },
    note: "예상 진화시간은 상황 정정으로 입력한 값을 쓰고 없으면 판정에서 제외한다. 시설피해 기준값은 매뉴얼 p.73 표를 확인해야 한다(목업 근사).",
  },

  astronomy: {
    sunrise: "06:31",
    sunset: "18:39",
    note: "의성 2025-03-22 근사값",
  },

  // 기상(기상청 단기예보 캐시). 통합 상황도 상단에 현재값과 수신 시각을 표시하고, 확산 예측·위험도·진화 전략의 입력으로 쓴다
  weather: {
    real: false,
    note: "발생 당시 풍속 5.6 m/s(보도)만 실제. 풍향(서남서)은 확산 방향 보도에서 추정, 시계열·습도·기온·시정은 합성.",
    source: "기상청 단기예보",
    base_time: "11:00",
    received_at: "2025-03-22T11:10:00+09:00",
    warnings: ["건조특보"],
    series: [
      {
        t: "12:00",
        wind_ms: 5.6,
        wind_dir: 240,
        rh: 24,
        temp_c: 19,
        vis_m: 8000,
      },
      {
        t: "13:00",
        wind_ms: 6.4,
        wind_dir: 240,
        rh: 21,
        temp_c: 21,
        vis_m: 6000,
      },
      {
        t: "14:00",
        wind_ms: 7.1,
        wind_dir: 245,
        rh: 19,
        temp_c: 22,
        vis_m: 4000,
      },
      {
        t: "15:00",
        wind_ms: 7.8,
        wind_dir: 250,
        rh: 18,
        temp_c: 22,
        vis_m: 3000,
      },
      {
        t: "16:00",
        wind_ms: 7.0,
        wind_dir: 245,
        rh: 20,
        temp_c: 21,
        vis_m: 4000,
      },
      {
        t: "17:00",
        wind_ms: 5.9,
        wind_dir: 240,
        rh: 26,
        temp_c: 19,
        vis_m: 6000,
      },
      {
        t: "18:00",
        wind_ms: 4.6,
        wind_dir: 235,
        rh: 33,
        temp_c: 16,
        vis_m: 8000,
      },
      {
        t: "19:00",
        wind_ms: 3.8,
        wind_dir: 230,
        rh: 40,
        temp_c: 13,
        vis_m: 9000,
      },
      {
        t: "20:00",
        wind_ms: 3.2,
        wind_dir: 225,
        rh: 46,
        temp_c: 11,
        vis_m: 10000,
      },
    ],
  },
  // P5가 겹친 상황을 가정한 공통 위험도 시연 결과
  risk_merge_demo: {
    enabled: false,
    mergedIds: ["F-2025-0322-01", "F-2025-0322-02"],
    missing_vars: [],
    scores: {
      weather: 4.5,
      terrain: 3.8,
      fuel: 4.1,
      infra: 3.0,
    },
    values: {
      weather: "풍속 7.0 m/s · 풍향 250° · 습도 20% · 기온 20℃",
      terrain: "경사 24° · 남서 사면 · 고도 260 m",
      fuel: "침엽수림(소나무) · 임목 밀도 높음 · 낙엽층 두꺼움",
      infra:
        "취약계층 180명(65세 이상 150명·0~14세 30명) · 최근 화선 기준 가장 가까운 소방서까지 거리 4.1 km",
    },
  },
  // 산불 위험도(UC-PRED-02): 4요인(기상·지형·연료·인프라) 점수 1~5의 가중평균 → 조건위험도 = 25 × (가중평균 − 1)
  // 요인 점수는 시연값(실서비스는 25개 변수 → 4요인 점수). 결측 변수는 제외하고 계산하며 목록을 함께 표시한다
  // 산불별 최대 위험도를 저장해(is_max) 종료 후에도 보여 준다. 사건별 요인 점수는 incidents[].risk_scores가 있으면 그것을 쓴다
  // 다음 확산예측 1회만 실패시키는 개발용 시연 설정
  prediction_demo: {
    mock_fail_next: false,
  },
  risk_model: {
    // 등급 실수 경계: 낮음 ≤50 · 보통 50 초과~65 · 높음 65 초과~85 · 매우 높음 85 초과
    // 개발용: true이면 다음 예측 완료 시 위험도 실패를 한 번 시연
    mock_fail_next: false,
    grades: [
      { name: "낮음", max: 50 },
      { name: "보통", max: 65 },
      { name: "높음", max: 85 },
      { name: "매우 높음", max: null },
    ],
    factors: [
      {
        key: "weather",
        name: "기상",
        weight: 0.372,
        score: 4.2,
        vars: "풍속·상대습도·기온·건조특보(기상청 단기예보)",
        values: null,
      },
      {
        key: "terrain",
        name: "지형",
        weight: 0.287,
        score: 3.6,
        vars: "경사·사면 방향·고도(DEM 30 m 격자)",
        values: "경사 21° · 남서 사면 · 고도 230 m",
      },
      {
        key: "fuel",
        name: "연료",
        weight: 0.266,
        score: 3.9,
        vars: "임상·임목 밀도·낙엽층(임상도)",
        values: "침엽수림(소나무) · 임목 밀도 높음 · 낙엽층 두꺼움",
      },
      {
        key: "infra",
        name: "인프라",
        weight: 0.074,
        score: 2.4,
        // 인구·소방서 거리는 화면 시연용 가상 예시
        vars: "취약계층 수(65세 이상·0~14세)·최근 화선에서 가장 가까운 소방서까지 거리",
        values:
          "취약계층 120명(65세 이상 100명·0~14세 20명) · 최근 화선 기준 가장 가까운 소방서까지 거리 3.2 km",
      },
    ],
    missing_vars: [],
    note: "기상 값은 기상청 단기예보 캐시, 지형·연료·인프라 값과 요인 점수는 시연값. 시연값 4.2·3.6·3.9·2.4 → 69.1(높음).",
  },

  // 합성 확산 모델: 확산속도(km/h) = a + b × 풍속(m/s). 발화점을 뒤쪽 초점으로 하는 타원 + 각도 노이즈
  fire_model: {
    head: [0.3, 0.16],
    flank: [0.08, 0.04],
    back: 0.06,
    noise_amp: 0.14,
  },

  // 마을: 좌표는 OSM 마을 중심점(실제). 인구·가구·고령·장애 수는 합성(안평면 2024 총인구 1,962명·평균나이 64.3세(SGIS)를 참고해 배분)
  villages: [
    {
      id: "goesan",
      name: "괴산리",
      emd: "안평면",
      lng: 128.60226,
      lat: 36.36565,
      pop: 84,
      hh: 47,
      elderly: 46,
      disabled: 3,
    },
    {
      id: "dook",
      name: "도옥리",
      emd: "안평면",
      lng: 128.60089,
      lat: 36.3535,
      pop: 92,
      hh: 51,
      elderly: 49,
      disabled: 4,
    },
    {
      id: "bakgok",
      name: "박곡리",
      emd: "안평면",
      lng: 128.61967,
      lat: 36.38298,
      pop: 138,
      hh: 74,
      elderly: 71,
      disabled: 6,
    },
    {
      id: "changgil",
      name: "창길리",
      emd: "안평면",
      lng: 128.59744,
      lat: 36.39479,
      pop: 121,
      hh: 66,
      elderly: 63,
      disabled: 5,
    },
    {
      id: "sinan",
      name: "신안리",
      emd: "안평면",
      lng: 128.61166,
      lat: 36.34063,
      pop: 105,
      hh: 58,
      elderly: 55,
      disabled: 4,
    },
    {
      id: "sinwol",
      name: "신월리",
      emd: "안평면",
      lng: 128.63824,
      lat: 36.35874,
      pop: 97,
      hh: 53,
      elderly: 52,
      disabled: 4,
    },
    {
      id: "seoktap",
      name: "석탑리",
      emd: "안평면",
      lng: 128.64337,
      lat: 36.38281,
      pop: 76,
      hh: 42,
      elderly: 41,
      disabled: 3,
    },
    {
      id: "majeon",
      name: "마전리",
      emd: "안평면",
      lng: 128.56532,
      lat: 36.36243,
      pop: 88,
      hh: 48,
      elderly: 45,
      disabled: 3,
    },
    {
      id: "daesa",
      name: "대사리",
      emd: "안평면",
      lng: 128.57405,
      lat: 36.34284,
      pop: 110,
      hh: 60,
      elderly: 57,
      disabled: 5,
    },
    {
      id: "cheolpa",
      name: "철파리",
      emd: "의성읍",
      lng: 128.67117,
      lat: 36.37326,
      pop: 412,
      hh: 205,
      elderly: 160,
      disabled: 12,
    },
    {
      id: "bangha",
      name: "방하리",
      emd: "단촌면",
      lng: 128.66258,
      lat: 36.39526,
      pop: 143,
      hh: 78,
      elderly: 79,
      disabled: 6,
    },
    {
      id: "secheon",
      name: "세촌리",
      emd: "단촌면",
      lng: 128.6614,
      lat: 36.42581,
      pop: 118,
      hh: 64,
      elderly: 66,
      disabled: 5,
    },
    {
      id: "hahwa",
      name: "하화리",
      emd: "단촌면",
      lng: 128.68771,
      lat: 36.41073,
      pop: 131,
      hh: 71,
      elderly: 70,
      disabled: 5,
    },
    {
      id: "sanghwa",
      name: "상화리",
      emd: "단촌면",
      lng: 128.7165,
      lat: 36.39835,
      pop: 96,
      hh: 52,
      elderly: 54,
      disabled: 4,
    },
  ],

  // 보호대상·취약시설
  facilities: [
    {
      id: "care1",
      name: "요양병원(위치 가상)",
      type: "care",
      lng: 128.5905,
      lat: 36.38,
      capacity: 70,
      real: false,
    },
    {
      id: "welfare1",
      name: "의성장애인복지센터",
      type: "welfare",
      lng: 128.68017,
      lat: 36.3596,
      capacity: 40,
      real: true,
    },
    {
      id: "heritage1",
      name: "고운사",
      type: "heritage",
      lng: 128.74883,
      lat: 36.45815,
      real: true,
    },
    {
      id: "temple1",
      name: "운람사",
      type: "temple",
      lng: 128.60624,
      lat: 36.3611,
      real: true,
    },
    {
      id: "school1",
      name: "의성북부초등학교",
      type: "school",
      lng: 128.6925,
      lat: 36.36137,
      real: true,
    },
  ],

  // 대피소: 좌표 실제(OSM), 수용 인원은 가상
  shelters: [
    {
      id: "sh1",
      name: "의성 실내체육관",
      lng: 128.70254,
      lat: 36.35664,
      capacity: 500,
    },
    {
      id: "sh2",
      name: "안평면사무소",
      lng: 128.58418,
      lat: 36.37676,
      capacity: 150,
    },
    {
      id: "sh3",
      name: "단촌면사무소",
      lng: 128.6743,
      lat: 36.42205,
      capacity: 150,
    },
    {
      id: "sh4",
      name: "봉양면사무소",
      lng: 128.57635,
      lat: 36.30072,
      capacity: 200,
    },
  ],

  // 유관기관(기관 레이어). 위치는 의성읍 중심부 근사값(가상)
  agencies: [
    {
      id: "ag1",
      name: "의성소방서",
      type: "fire",
      lng: 128.695,
      lat: 36.352,
      real: false,
    },
    {
      id: "ag2",
      name: "의성경찰서",
      type: "police",
      lng: 128.699,
      lat: 36.356,
      real: false,
    },
    {
      id: "ag3",
      name: "의성군청(통합지휘본부)",
      type: "gov",
      lng: 128.6971,
      lat: 36.3528,
      real: false,
    },
    {
      id: "ag4",
      name: "한국전력 의성지사",
      type: "kepco",
      lng: 128.692,
      lat: 36.348,
      real: false,
    },
  ],

  // 송전선: OSM power=line 이 로드되면(data_osm_lines.js) 그것을 쓰고, 없으면 아래 가상 선형
  power_line_fallback: {
    name: "송전선(가상 선형)",
    real: false,
    coords: [
      [128.575, 36.345],
      [128.605, 36.372],
      [128.64, 36.392],
      [128.675, 36.408],
    ],
  },

  // 대피로·진입로: 선형은 가상(개략선). 겹침 구간 판정은 이 데이터로 고정
  routes: [
    {
      id: "evac-A",
      kind: "evac",
      name: "대피로: 박곡리 → 의성 실내체육관",
      coords: [
        [128.61967, 36.38298],
        [128.635, 36.378],
        [128.655, 36.372],
        [128.68, 36.365],
        [128.70254, 36.35664],
      ],
    },
    {
      id: "access-1",
      kind: "access",
      name: "진화차량 진입로: 의성소방서 → 발화점",
      coords: [
        [128.695, 36.352],
        [128.68, 36.365],
        [128.655, 36.372],
        [128.635, 36.378],
        [128.615, 36.372],
        [128.60226, 36.36565],
      ],
    },
    {
      id: "conflict",
      kind: "conflict",
      name: "대피로·진입로 겹침 구간",
      coords: [
        [128.635, 36.378],
        [128.655, 36.372],
        [128.68, 36.365],
      ],
    },
  ],

  // 진화자원(UC-ADMIN-02가 관리하는 데이터. 재난 시 자원 현황(UC-SIT-03)과 S3 자원 배분 제안의 공급원). 전부 가상
  // type: 헬기 | 차량 | 인력   status: 투입 | 대기 | 정비   qty: 인력은 명, 헬기·차량은 1   base: 배치 위치(평소 대기 장소)
  // 필수 값: 구분·명칭(호출부호)·소속·수량
  resources: [
    {
      id: "r01",
      type: "헬기",
      name: "KFS-H01",
      org: "산림항공본부(안동)",
      base: "안동 산림항공관리소",
      qty: 1,
      status: "투입",
    },
    {
      id: "r02",
      type: "헬기",
      name: "KFS-H02",
      org: "산림항공본부(안동)",
      base: "안동 산림항공관리소",
      qty: 1,
      status: "투입",
    },
    {
      id: "r03",
      type: "헬기",
      name: "KFS-H03",
      org: "산림항공본부(울진)",
      base: "울진 산림항공관리소",
      qty: 1,
      status: "투입",
    },
    {
      id: "r04",
      type: "헬기",
      name: "KFS-H04",
      org: "경북도 임차헬기",
      base: "의성 임차헬기 계류장",
      qty: 1,
      status: "투입",
    },
    {
      id: "r05",
      type: "헬기",
      name: "KFS-A01",
      org: "산림항공본부(안동)",
      base: "안동 산림항공관리소",
      qty: 1,
      status: "대기",
    },
    {
      id: "r06",
      type: "헬기",
      name: "KFS-A02",
      org: "산림항공본부(안동)",
      base: "안동 산림항공관리소",
      qty: 1,
      status: "대기",
    },
    {
      id: "r07",
      type: "헬기",
      name: "KFS-A03",
      org: "산림항공본부(울진)",
      base: "울진 산림항공관리소",
      qty: 1,
      status: "대기",
    },
    {
      id: "r08",
      type: "헬기",
      name: "KFS-A04",
      org: "산림항공본부(울진)",
      base: "울진 산림항공관리소",
      qty: 1,
      status: "대기",
    },
    {
      id: "r09",
      type: "헬기",
      name: "KFS-A05",
      org: "경북도 임차헬기",
      base: "의성 임차헬기 계류장",
      qty: 1,
      status: "대기",
    },
    {
      id: "r10",
      type: "헬기",
      name: "KFS-A06",
      org: "경북도 임차헬기",
      base: "의성 임차헬기 계류장",
      qty: 1,
      status: "대기",
    },
    {
      id: "r11",
      type: "헬기",
      name: "KFS-M01",
      org: "산림항공본부(안동)",
      base: "안동 산림항공관리소",
      qty: 1,
      status: "정비",
    },
    {
      id: "r12",
      type: "인력",
      name: "산불전문진화대 1조",
      org: "의성군",
      base: "의성군청",
      qty: 20,
      status: "투입",
      pos: [128.607, 36.368],
    },
    {
      id: "r13",
      type: "인력",
      name: "산불전문진화대 2조",
      org: "의성군",
      base: "의성군청",
      qty: 20,
      status: "투입",
      pos: [128.612, 36.371],
    },
    {
      id: "r14",
      type: "인력",
      name: "산불전문진화대 3조",
      org: "의성군",
      base: "의성군청",
      qty: 20,
      status: "투입",
      pos: [128.598, 36.36],
    },
    {
      id: "r15",
      type: "인력",
      name: "산불전문진화대 4조",
      org: "의성군",
      base: "의성군청",
      qty: 20,
      status: "대기",
    },
    {
      id: "r16",
      type: "인력",
      name: "공중진화대 1조",
      org: "산림항공본부",
      base: "안동 산림항공관리소",
      qty: 15,
      status: "대기",
    },
    {
      id: "r17",
      type: "인력",
      name: "특수진화대 1조",
      org: "남부지방산림청",
      base: "남부지방산림청(안동)",
      qty: 15,
      status: "대기",
    },
    {
      id: "r18",
      type: "차량",
      name: "의성 펌프 1",
      org: "의성소방서",
      base: "의성소방서",
      qty: 1,
      status: "투입",
    },
    {
      id: "r19",
      type: "차량",
      name: "의성 펌프 2",
      org: "의성소방서",
      base: "의성소방서",
      qty: 1,
      status: "투입",
    },
    {
      id: "r20",
      type: "차량",
      name: "의성 물탱크 1",
      org: "의성소방서",
      base: "의성소방서",
      qty: 1,
      status: "투입",
    },
    {
      id: "r21",
      type: "차량",
      name: "의성 물탱크 2",
      org: "의성소방서",
      base: "의성소방서",
      qty: 1,
      status: "투입",
    },
    {
      id: "r22",
      type: "차량",
      name: "안평 119안전센터 펌프",
      org: "의성소방서",
      base: "안평 119안전센터",
      qty: 1,
      status: "투입",
    },
    {
      id: "r23",
      type: "차량",
      name: "산불진화차 1",
      org: "의성군",
      base: "의성군청 차고",
      qty: 1,
      status: "투입",
    },
    {
      id: "r24",
      type: "차량",
      name: "산불진화차 2",
      org: "의성군",
      base: "의성군청 차고",
      qty: 1,
      status: "투입",
    },
    {
      id: "r25",
      type: "차량",
      name: "산불진화차 3",
      org: "의성군",
      base: "의성군청 차고",
      qty: 1,
      status: "투입",
    },
    {
      id: "r26",
      type: "차량",
      name: "안동 펌프 1",
      org: "안동소방서(응원)",
      base: "안동소방서",
      qty: 1,
      status: "대기",
    },
    {
      id: "r27",
      type: "차량",
      name: "안동 물탱크 1",
      org: "안동소방서(응원)",
      base: "안동소방서",
      qty: 1,
      status: "대기",
    },
    {
      id: "r28",
      type: "차량",
      name: "산불진화차 4",
      org: "의성군",
      base: "의성군청 차고",
      qty: 1,
      status: "정비",
    },
  ],

  // 계정(UC-ADMIN-01이 관리, UC-AUTH-01의 계정 공급원). 전부 가상. 아이디·비밀번호·사용자 구분이 모두 맞아야 진입한다
  // 권한: 조작(commander)·열람(viewer)·보고(reporter)·관리(admin). 관리 계정은 설치 시 사전 발급, 나머지는 전산 관리자가 발급(아이디·초기 비밀번호는 시스템 생성)
  accounts: [
    {
      id: "cmd01",
      pw: "1234",
      name: "통합지휘권자 1",
      org: "의성군",
      role: "commander",
      status: "발급",
      issued: "2025-03-02",
    },
    {
      id: "view01",
      pw: "1234",
      name: "열람자 1(유관기관)",
      org: "의성경찰서",
      role: "viewer",
      status: "발급",
      issued: "2025-03-02",
    },
    {
      id: "view02",
      pw: "1234",
      name: "열람자 2(상급 본부)",
      org: "경상북도",
      role: "viewer",
      status: "회수",
      issued: "2025-01-15",
    },
    {
      id: "rep01",
      pw: "1234",
      name: "상황 보고자 1(현장)",
      org: "의성군 산림과",
      role: "reporter",
      status: "발급",
      issued: "2025-03-02",
    },
    {
      id: "admin01",
      pw: "1234",
      name: "전산 관리자",
      org: "의성군 정보통신과",
      role: "admin",
      status: "발급",
      issued: "2025-01-02",
    },
  ],

  // 근거 청크(요약). 원문 비공개이므로 쪽수 + 요약만 둔다
  evidence: {
    "SM-p013": {
      doc: "표준매뉴얼",
      page: "p.13",
      section: "대응단계의 목적",
      text: "대응단계는 초기 진화와 동원할 진화자원의 규모를 정하기 위해 발령한다.",
    },
    "SM-p022": {
      doc: "표준매뉴얼",
      page: "p.22",
      section: "대응단계 발령",
      text: "대응단계는 산림청장이 자체 평가와 산불현장 통합지휘본부 협의를 거쳐 발령한다. 통합지휘본부장은 소방·경찰·군의 장비와 인력을 동원하고 산불현장 대책회의에서 기관별 임무를 부여한다.",
    },
    "SM-p041": {
      doc: "표준매뉴얼",
      page: "p.41",
      section: "통합지휘본부 반별 역할",
      text: "상황총괄반은 현장 영상과 확산예측으로 상황을 분석해 진화전략도를 작성하고 자원을 배정한다. 지상진화반은 진화구역을 설정하고 구역별 진화율에 따라 자원을 재배치한다.",
    },
    "SM-p065": {
      doc: "표준매뉴얼",
      page: "p.65",
      section: "주민대피경로카드",
      text: "행정리별 주민대피경로카드에 대피장소, 비상 집결지, 버스 진입·회차 공간, 위험 요소, 이동거리·시간을 둔다.",
    },
    "SM-p072": {
      doc: "표준매뉴얼",
      page: "p.72",
      section: "지휘권자",
      text: "초기대응·확산대응 1단계는 시장·군수·구청장(국유림관리소장)이 지휘하고, 2단계와 2개 이상 시·군·구에 걸친 산불은 시·도지사가, 2개 이상 시·도에 걸치면 산림청장이 지휘한다. 신고·접수 시 헬기 2대 투입이 원칙이다.",
    },
    "SM-p073": {
      doc: "표준매뉴얼",
      page: "p.73",
      section: "대응단계 판단기준",
      text: "대응단계 판단기준은 피해면적, 평균풍속, 예상 진화시간, 시설피해 4요소이며 하나라도 상위 기준을 충족하면 상위 단계를 검토한다. 확산대응 1단계는 피해면적 10 ha 이상 100 ha 미만, 2단계는 100 ha 이상(시행령 별표 요약).",
    },
    "SM-p074": {
      doc: "표준매뉴얼",
      page: "p.74~76",
      section: "위험구역과 주민대피",
      text: "화선 도달 5시간 이내 지역은 위험구역으로 즉시 실행 대피명령, 8시간 이내는 잠재 위험구역으로 실행 대기 대피명령을 내린다. 야간이 위험구역 시간대에 포함되면 일몰 전에 사전대피한다. 요양원·장애인시설 등 취약시설이 인접하면 위험구역에 포함한다. 대피명령은 마을·읍면동 단위로 내린다.",
    },
    "SM-p077": {
      doc: "표준매뉴얼",
      page: "p.77",
      section: "진화 우선순위·헬기·안전",
      text: "진화 우선순위는 ① 인명 ② 국가기간산업·군사시설·국가유산 ③ 가옥 등 재산 ④ 중요 산림자원 ⑤ 기타 산림 순이다. 가용 진화헬기를 집중 투입하고 공중진화대·특수진화대를 즉시 출동시킨다. 투입 전 임무를 부여하고 진화복·안전장구를 확인하며 위치추적장치를 휴대한다.",
    },
    "SM-p078": {
      doc: "표준매뉴얼",
      page: "p.78",
      section: "진화 방식·자원 투입",
      text: "강풍·동시다발로 헬기 운용이 어려우면 지상진화에 집중하고, 풍속이 잦아드는 일몰 후·일출 전에 집중 진화하며, 강풍 해제 시 헬기 재투입을 준비한다. 확산 정도에 따라 진화자원을 단계적으로 투입하고 인접 시·군 자원을 동원한다.",
    },
    "SM-p078b": {
      doc: "표준매뉴얼",
      page: "p.78~79",
      section: "재난문자·자막방송",
      text: "긴급재난문자(CBS)와 자막방송(DITS)을 산불 발생, 대피 권고, 대피 명령 시 단계별로 송출한다. 인명·민가 피해 우려가 없으면 생략할 수 있다.",
    },
    "SM-p079": {
      doc: "표준매뉴얼",
      page: "p.79",
      section: "시설 보호·취약계층",
      text: "주택 등 보호대상 시설물 주변에 소방차 등 진화장비를 집중 배치하고 헬기로 인접 산림에 예비 살수한다. 안전취약계층을 우선 대피시킨다.",
    },
    "SM-p084": {
      doc: "표준매뉴얼",
      page: "p.84",
      section: "주민대피 명령",
      text: "시장·군수·구청장이 주민대피를 명령하며, 대피하지 않은 주민은 강제로 대피시킨다.",
    },
    "SM-p095": {
      doc: "표준매뉴얼",
      page: "p.95",
      section: "한전 협조",
      text: "한전은 송전시설의 전류 차단과 우회선로 확보를 맡고 통합지휘본부에 협력관을 파견한다.",
    },
    "SM-p118": {
      doc: "표준매뉴얼",
      page: "p.118",
      section: "인명피해 판단 요소",
      text: "인명피해 가능성은 풍속·풍향, 진화인력, 지형, 연료를 보고 판단하며, 인명·국가유산·고압선 피해 여부와 확대 가능성을 판단한다.",
    },
    "SM-p119": {
      doc: "표준매뉴얼",
      page: "p.119",
      section: "유관기관 주요 기능",
      text: "경찰은 초기대응에서 교통통제와 주민대피 지원을 맡는다. 소방은 접근 곤란 지역 인명구조·대피계획, 수색·구조·구급을 맡는다.",
    },
    "SM-p021": {
      doc: "표준매뉴얼",
      page: "p.21",
      section: "긴급구조통제단",
      text: "긴급구조는 소방의 긴급구조통제단장이 긴급구조기관의 역할을 분담해 지휘한다.",
    },
  },

  // 결정 항목 카탈로그: 진화 S1~S7(UC-PROP-01), 대피 E1~E7(UC-PROP-02)
  catalog: [
    {
      id: "S1",
      axis: "진화",
      name: "대응단계 판단·격상 검토",
      authority: "협의",
    },
    {
      id: "S2",
      axis: "진화",
      name: "진화 우선지역·보호대상 선정",
      authority: "직접",
    },
    {
      id: "S3",
      axis: "진화",
      name: "진화자원 투입·배분·재배치",
      authority: "직접",
    },
    {
      id: "S4",
      axis: "진화",
      name: "진화 방식·시간대 전략",
      authority: "직접",
    },
    { id: "S5", axis: "진화", name: "시설 보호 조치", authority: "직접/요청" },
    {
      id: "S6",
      axis: "진화",
      name: "유관기관 동원·협조 요청",
      authority: "직접/요청",
    },
    {
      id: "S7",
      axis: "진화",
      name: "진화인력 안전·투입 관리",
      authority: "직접",
    },
    { id: "E1", axis: "대피", name: "위험구역 설정", authority: "직접" },
    {
      id: "E2",
      axis: "대피",
      name: "대피 대상·순서·시점 결정",
      authority: "직접",
    },
    {
      id: "E3",
      axis: "대피",
      name: "취약시설·미대피 주민 조치",
      authority: "직접",
    },
    { id: "E4", axis: "대피", name: "대피소 배정·분산", authority: "직접" },
    { id: "E5", axis: "대피", name: "대피 경로·교통통제", authority: "요청" },
    {
      id: "E6",
      axis: "대피",
      name: "재난문자·방송 전파 제안",
      authority: "직접",
    },
    {
      id: "E7",
      axis: "대피",
      name: "인명구조·긴급구조 요청",
      authority: "요청",
    },
  ],
};
